### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by e-p-n** [Envoy-products/Envoy-Products#111]
- Footer no longer stretches all the way to the right side of the screen

**Comment by samiul1988** [comment]
![image](https://user-images.githubusercontent.com/3344833/112604879-4aab6480-8ddc-11eb-974b-2d16738f8a00.png)

**Comment by e-p-n** [comment]
I think I have resolved this. Should show in my next pull request. But I want to deal with the other pull requests and merge before I add mine
