### ISSUE TITLE
Find Content - Nathan

### ISSUE THREAD

**Issue by e-p-n** [Envoy-products/Envoy-Products#14]
- Find five products to feature on the site
- Write one blog post

**Comment by nchow18** [comment]
1. https://www.blueland.com/collections/our-kits/products/the-clean-up-kit?utm_source=RAN&utm_medium=affiliates&utm_campaign=10&utm_content=TnL5HPStwNw&ranMID=44816&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-nIlvmjNcdES8RTIhyKlI4w

2. https://byhumankind.com/products/shampoo?irclickid=Q8sWAdUFVxyLUl80TbWK8Xs3UkEVpn0hrS2cyE0&irgwc=1&utm_source=affiliate&utm_medium=referral&utm_campaign=Skimbit%20Ltd._bestproducts.com&utm_term=Online%20Tracking%20Link

3. https://www.amazon.ca/dp/B07LFLLBSP?ots=1&ascsubtag=[artid|2089.g.1435[src|[ch|[lt|&linkCode=gs2&tag=hearstmagazin-20

4. https://sqwishful.com/products/pop-up-sponges

5. https://www.amazon.ca/dp/B06X9JXK3Y?ots=1&ascsubtag=[artid|2089.g.1435[src|[ch|[lt|&linkCode=gs2&tag=hearstmagazin-20

**Comment by nchow18** [comment]
update blogpost:
